name: VLC-ESBMC-Test

on: push

jobs:
  esbmc-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: install dependencies
        run: |
          wget -O libevent.tar.gz https://github.com/libevent/libevent/releases/download/release-2.1.12-stable/libevent-2.1.12-stable.tar.gz
          tar -xf libevent.tar.gz
          wget -O ncurses.tar.gz https://invisible-mirror.net/archives/ncurses/ncurses-6.5.tar.gz
          tar -xf ncurses.tar.gz
          ls
          cd libevent-2.1.12-stable
          ls
      
      - name: run esbmc action
        uses: esbmc/esbmc-action@v1
        with:
          esbmc-options: --incremental-bmc --include-file tmux.h
      
      - run: ls
        
